// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZBOZo9JzLZ8szFRHTlFhl8OL_fGI6PM',
    appId: '1:715926020479:web:ef38911748213b1990ba4a',
    messagingSenderId: '715926020479',
    projectId: 'redite-clone',
    authDomain: 'redite-clone.firebaseapp.com',
    storageBucket: 'redite-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDwAVNPhNa1DCkAK6kiXH3tDQLxVXdcs',
    appId: '1:715926020479:android:0cf45713648bea7c90ba4a',
    messagingSenderId: '715926020479',
    projectId: 'redite-clone',
    storageBucket: 'redite-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxQ1R2O2ewVR20LhHa8aXHprpF69Lr7NI',
    appId: '1:715926020479:ios:87e616ec1fabf14290ba4a',
    messagingSenderId: '715926020479',
    projectId: 'redite-clone',
    storageBucket: 'redite-clone.appspot.com',
    iosClientId: '715926020479-bb5n14g4lj1j2prmjuv6bo8d2iki26dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.rediteClone',
  );
}
